---
title: Perdana Hadi Sanjaya
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: perdanahadisanjaya@gmail.com
description: An opininated blog about Software & Cloud Development
author: Perdana Hadi Sanjaya
baseurl: "/"
url: http://perdanahadi.com
twitter_username: perdanahadii
github_username: perdanahadii
facebook_username: 
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
- jekyll-feed
- jekyll-paginate
